#!/usr/bin/env node

var express = require('express');
var app = express();

app.use(express.static('./'));

var http = require('http');

var port = process.env.PORT || 80;
app.set('port', port);

var server = http.createServer(app);
server.listen(port);